#!/usr/bin/env bash
# Check if the correct number of arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE=path_to_file
IP=server_ip
USERNAME=server-user_name
SSH_KEY=path_to_private_key

#transfering the file to the server using the scp command
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME@$IP":~

# Check if the scp command was successful
if [ "$?" -eq 0 ]; then
    echo "File transferred successfully to $USERNAME@$IP:~/$FILE"
else
    echo "Error: File transfer failed"
    exit 1
fi

exit 0
