#!/usr/bin/env bash
# Installs Nginx with the following requirements/configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++   at the root with a curl GET request.

#  updates the package lists for available software packages.
apt-get update
# installs the Nginx web server.
apt-get install -y nginx
#  sets the content of the index.html file to "Hello World!" using the 'echo' command
echo "Hello World!" > /etc/nginx/html/index.html
# Sets Nginx to listen on port 80 and serve files from the /etc/nginx/html directory.
printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     
     server_name _;

     root        /etc/nginx/html;
     index       index.html index.htm index.nginx-debian.html;
}
" > /etc/nginx/sites-available/default

# Restarts the Nginx service to apply the configurations updates.
service nginx restart
