#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Displays only the part of the name after the first dash. 

list_f=$(ls)
for i in $list_f; do
  echo "$i" | cut -d '-' -f2
done
